### ISSUE TITLE
How to run run.sh ?

### ISSUE THREAD

**Issue by yashwantptl7** [tmulc18/Distributed-TensorFlow-Guide#12]
While doing distributed training in multiple computers, do I need to run run.sh in PS or in each computer separately ?  BTW both of these cases are not working. When I run my code in single computer with multiple workers it works properly. But I don't know how to run it on multiple computers. Is cluster manager(like Kubernets) required for this purpose?

**Comment by tmulc18** [comment]
It is not required, but it would make launching jobs much easier.  You can log into each computer and start the job (not the `run.sh`, but the python code), but you need to configure the network correctly.  The example files assume the same computer is used.

**Comment by yashwantptl7** [comment]
I have tried that also(log into each computer and start job), but worker was unable to connect with a log saying "CreateSession still waiting for response from worker: /job:worker/replica:0/task:1". HOw do i resolve that?

**Comment by tmulc18** [comment]
I'm not sure what your network setup is.  Did you correctly configure the ip addresses in the cluster setup?

**Comment by yashwantptl7** [comment]
I have two systems connected via LAN. And my cluster setup is
"cluster = tf.train.ClusterSpec({"ps":['10.229.25.219:2222'] , "worker":['10.229.25.253:2223','10.229.25.253:2224']})". What else do I need to do?

**Comment by yashwantptl7** [comment]
solved this by upgrading python version to 3.6
