### ISSUE TITLE
No way to feed different mini-batch data to the graph for local optimizer to update local variables in the DOWNPOUR example

### ISSUE THREAD

**Issue by raven1989** [tmulc18/Distributed-TensorFlow-Guide#8]
The example is brilliant and inspires me a lot. 
However it didn't show how to feed data to the graph.
In real practice, I find it impossible to feed **different** mini-batch data for local optimizer to compute gradients each window-time. Here's what I mean:
It's easy to feed data to the graph by
`session.run([opt, ...], feed_dict={})`
I think every time session.run(... , feed_dict={...}) is called, the graph uses the same feed_dict to compute gradients by local optimizer window times, although the gradients turn out to be different because last gradients have been applied to local variables the time before this one. However, the feed_dict is the same batch which computed window times then summed up as one set of gradients to apply to the global variables.
I notice that this is different from the pseudocode described in the paper "Large Scale Distributed Deep Networks", and I quote:
```
Algorithm 7.1: DOWNPOURSGDCLIENT(α, nfetch, npush)

procedure STARTASYNCHRONOUSLYFETCHINGPARAMETERS(parameters)
    parameters ← GETPARAMETERSFROMPARAMSERVER()

procedure STARTASYNCHRONOUSLYPUSHINGGRADIENTS(accruedgradients)
    SENDGRADIENTSTOPARAMSERVER(accruedgradients)
    accruedgradients ← 0

main
global parameters, accruedgradients
step ← 0
accruedgradients ← 0
while true
do
    if (step mod nfetch) == 0
        then STARTASYNCHRONOUSLYFETCHINGPARAMETERS(parameters)
    **data ← GETNEXTMINIBATCH()**
    gradient ← COMPUTEGRADIENT(parameters, data)
    accruedgradients ← accruedgradients + gradient
    parameters ← parameters − α ∗ gradient
    if (step mod npush) == 0
        then STARTASYNCHRONOUSLYPUSHINGGRADIENTS(accruedgradients)
    step ← step + 1
```
In the pseudocode, every time a mini-batch data is fetched before computing gradients no matter this time is the time to apply them to global variables or not, this is what I bold **different** mini-batch.

Is there a way to achieve this?

**Comment by tmulc18** [comment]
Yes, you are correct.  The examples don't show how to do different minibatches and I can see how it appears different from the papers.  The optimization problem in the provided examples isn't like most DL optimization problems that require minibatches, which is why that detail was omitted.  You can have different minibatches by having an array where each element of that array will be a placeholder for a minibatch.  Then you can also have an array of losses where each element is the loss for one minibatch.  Finally, make sure that the _t_th local optimization step is taking the _t_th loss as its argument.  Does that make sense?

**Comment by raven1989** [comment]
Sorry for the late reply. Using multiple sets of placeholders does work. I think, in a sense, this is a in-graph replica solution. A million thanks!!

**Comment by tmulc18** [comment]
Not a problem.  Glad the solution is working! Yes, I think this is in-graph replication :)  I'm going to close this issue, but feel free to reopen it if you need a better solution.
